name: 'Set up Node.js and install deps/fetch cache'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with: { node-version: '18', cache: 'yarn' }
    - name: Yarn install deps from lockfile
      shell: bash
      run: yarn --frozen-lockfile
