name: setup-node
description: Set up Node.js and install deps/fetch cache
inputs:
  cacheVersion:
    description: 'Version of the cached dependencies. Change it to create a new cache'
    required: false
    default: "v1"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with: { node-version: '18', registry-url: 'https://registry.npmjs.org' }
    - uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ inputs.cacheVersion }}
    - run: yarn --frozen-lockfile
      shell: bash

