name: 'Set up Nodejs 16.10 and install deps/fetch cache '

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with: { node-version: "16.10", cache: 'yarn' }
    - name: Yarn install deps from lockfile
      shell: bash
      run: yarn --frozen-lockfile
