name: 'Set up Nodejs 16.10 and install deps/fetch cache '

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with: { node-version: "16.10", cache: 'yarn' }
      env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" } }
    - name: Yarn install deps from lockfile
      run: yarn --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
