name: git-push-if-needed
description: 'Note: if run on protected branch, code must be checked out with admin PAT for this push to work'

# Only used in `snowflake` repo
# todo: refactor to ci-typescript bin script instead

runs:
  using: "composite"
  steps:
    - run: |
        ahead=`git rev-list HEAD --not --remotes | wc -l | awk '{print $1}'`
        echo ahead=$ahead
        [ "$ahead" != "0" ] && git push --set-upstream origin ${GITHUB_REF##*/} && echo "pushed, exiting" && exit 0
        [ "$ahead" != "0" ] && echo "Failed to push, failing job" && exit 1
        echo "nothing to push, proceeding"
      shell: bash
