name: 'Sets generic CI env vars'

runs:
  using: "composite"
  steps:
    - name: Set CI_BRANCH
      run: echo "CI_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV
    - name: Set CI_REPO
      run: echo "CI_REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV # Override branch env var
    - name: Set CI_JOB
      run: echo "CI_JOB=${GITHUB_JOB}" >> $GITHUB_ENV # Override branch env var