name: test-reporter
description: 'Upload test artifacts to github'
# TODO: Make github format it nicely, this is currently just a wrapper to simplify future addition
inputs:
  name:
    description: Name of the check run
    required: true
  path:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.name }}"
        path: "${{ inputs.path }}"
