name: 'Set up Nodejs 16 and install deps/fetch cache '

runs:
  using: "composite"
  steps:
    - { uses: actions/checkout@v3, with: { persist-credentials: false } }
    - { uses: NaturalCycles/actions/commands/setup-node@v1 }
    - name: build
      run: yarn build
    - name: test
      run: yarn test-ci

