name: setup-python
description: 'Set up python 3.10 and install deps/fetch cache '

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4' # 3.10.5 changed default AGENT_TOOLSDIRECTORY and broke install
      # Roll out 3.10.5 more carefully
#      env:
#        AGENT_TOOLSDIRECTORY: "/home/docker/actions-runner/_work/_tool/py-hostedtoolcache"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation}}/lib/python3.10/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          v2-${{ runner.os }}-pip-
          v2-${{ runner.os }}-
    - name: Install pip dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pip3 install --upgrade -r requirements.txt
