name: 'Set up python 3.10 and install deps/fetch cache using Poetry'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
    # - name: Cache poetry virtualenv
    #   uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: ${{ env.pythonLocation }}
    #     key: ${{ runner.os }}-poetry-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}
    - name: Install poetry
    #  if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install --upgrade pip
        pip install poetry
      shell: bash
    # - name: Set poetry config
    #   run: python -m poetry config virtualenvs.create false
      shell: bash
    - name: Install dependencies
    #  if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install
      shell: bash
