name: 'GIT_MSG'
description: 'exports first line of last commit message to output msg'
outputs:
  msg:
    description: "Output of last git commit message"
    value: ${{ steps.msg.outputs.msg }}
runs:
  using: "composite"
  steps:
    - run: echo "msg=`git log -1 --pretty=%B | head -n 1`" >> $GITHUB_OUTPUT
      id: msg
      shell: bash
    - run: echo "GIT_MSG=`git log -1 --pretty=%B | head -n 1`" >> $GITHUB_ENV
      shell: bash
